GET http://localhost:5001

###
GET http://localhost:5001/hello

###
GET http://localhost:5001/movies/hello

###
POST http://localhost:5001/api/register
Content-Type: application/json

{
    "name": "Rakesh",
    "email": "admin@standardbredtrader.com.au",
    "passworkd": "XaWaJBgfb2AgoNFR"
}

###
POST http://localhost:5001/api/login
Content-Type: application/json

{
    "email": "admin@standardbredtrader.com.au",
    "passworkd": "XaWaJBgfb2AgoNFR"
}
