### Create a login Token
POST http://localhost:8001/login
Content-Type: application/json
{
    "username": "john",
    "role": "admin",
    "domain": ""
}

### Sign Up
POST http://localhost:8001/api/v1/auth/signup
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@xmate.com.au",
  "password": "Hellodemo@123"
}

### Login Up
POST http://localhost:8001/api/v1/auth/login
Content-Type: application/json

{
  "loginKey": "vikcy.vikashkumar@gmail.com", 
  "password": "Hellodemo@123"
}

### forgot password
POST http://localhost:8001/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "vikcy.vikashkumar@gmail.com"
}

### Get My Profile
GET http://localhost:8001/api/v1/auth/userprofile
Content-Type: application/json,
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY3Mzg4MDM5LCJleHAiOjE3Njc5OTI4Mzl9.LyObQ4fKIGk5QWZkJ8zrC0gB6AL1Vp21DEoMEFqgPu8

### Get members
GET http://localhost:8001/api/v1/members
Content-Type: application/json,
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY3Mzg4MDM5LCJleHAiOjE3Njc5OTI4Mzl9.LyObQ4fKIGk5QWZkJ8zrC0gB6AL1Vp21DEoMEFqgPu8

### Get single horse details
GET http://localhost:8001/api/v1/pedigree?horseid=528492

### Get All Horses with token
GET http://localhost:8001/api/v1/horses
Content-Type: application/json,
Authorization: Bearer token

### Get All Horses with token
GET http://localhost:8001/api/v1/horsesearch?page=1&limit=50

### Get Real Horses
GET http://localhost:8001/api/v1/horses/real?horseid=528492&gen=3

### Get Real Horses
GET http://localhost:8001/api/v1/horses/real?horseid=&gen=6

### Get Hypothetical Horses
GET http://localhost:8001/api/v1/horses/hypo?sireid=497875&damid=376952&gen=4

### Get Hypothetical Horses
GET http://localhost:8001/api/v1/horses/hypo?sireid=278550&damid=499163&gen=6


### Get All Plans
GET http://localhost:8001/api/v1/plans

### Get All Horses with token
GET http://localhost:8001/api/v1/horses?page=1&limit=50
Content-Type: application/json
Authorization: Bearer token

### Get Pedigree of ID 4
GET http://localhost:8001/api/v1/horses/4/pedigree

### Create a Horse
POST http://localhost:8001/api/v1/horses
Content-Type: application/json

{
    "name": "New Colt",
    "sex": "Stallion",
    "sire_id": 1
}

### Get All Members
GET http://localhost:8001/api/v1/members



### Get user
GET http://localhost:8001/users
Content-Type: application/json,
Authorization: Bearer token