### Create a login Token
POST http://localhost:8001/login
Content-Type: application/json

{
    "username": "john",
    "role": "admin",
    "domain": ""
}

### Get All Horses with token
GET http://localhost:8001/api/v1/horses
Content-Type: application/json,
Authorization: Bearer token

### Get All Horses with token
GET http://localhost:8001/api/v1/horsesearch?page=1&limit=50

### Get Real Horses
GET http://localhost:8001/api/v1/horses/real?horseid=&gen=6


### Get Real Horses
GET http://localhost:8001/api/v1/horses/hypo?sireid=497875&damid=376952&gen=4

### Get All Horses with token
GET http://localhost:8001/api/v1/horses?page=1&limit=50
Content-Type: application/json
Authorization: Bearer token

### Get Pedigree of ID 4
GET http://localhost:8001/api/v1/horses/4/pedigree

### Create a Horse
POST http://localhost:8001/api/v1/horses
Content-Type: application/json

{
    "name": "New Colt",
    "sex": "Stallion",
    "sire_id": 1
}

### Get All Members
GET http://localhost:8001/api/v1/members



### Get user
GET http://localhost:8001/users
Content-Type: application/json,
Authorization: Bearer token